// Generated by GraphQL Code Generator from graphql/cms/homepage.graphql.
//
// Hand-edited twice, deliberately, because `yarn gen` needs a running Strapi to
// introspect the schema and this file is committed so the app builds without
// one:
//   1. the media `width`/`height` fields were added alongside the .graphql
//      document. The operation result type is an alias of the schema types,
//      which already carry those fields, so no type changes were needed;
//   2. the React hooks were removed. The homepage is prerendered on the server
//      and runs no client-side query, so shipping `useHomePageQuery` would be
//      dead code. `graphql.config.yml` is configured to stop emitting them.
import * as Types from '../types';

import { gql } from '@apollo/client';
export type HomePageQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type HomePageQuery = { __typename?: 'Query', homePage?: Types.HomePageEntityResponse | null };


export const HomePageDocument = gql`
    query HomePage {
  homePage {
    data {
      attributes {
        sections {
          ... on ComponentCommonHeader {
            id
            Text
            ButtonText
            ButtonLink
          }
          ... on ComponentCommonCarousel {
            id
            Item {
              ... on ComponentCommonTwoColumnBlock {
                id
                TitleText
                Description
                ButtonText
                ButtonUrl
                ImagePosition
                Image {
                  data {
                    id
                    attributes {
                      url
                      previewUrl
                      alternativeText
                      width
                      height
                    }
                  }
                }
              }
            }
          }
          ... on ComponentCommonTwoColumnBlock {
            id
            TitleText
            Description
            ButtonText
            ButtonUrl
            ImagePosition
            Image {
              data {
                id
                attributes {
                  url
                  previewUrl
                  alternativeText
                  width
                  height
                }
              }
            }
          }
          ... on Error {
            code
            message
          }
        }
      }
    }
  }
}
    `;
